# -*- coding: utf-8 -*-
"""ibrary_Management_System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WGRCEnECdG-zw7GGfAezLjsYmHf1Ftep
"""

class Library:
    def __init__(self):
        self.file = open("book.txt", "a+")

    def __del__(self):
        self.file.close()

    def add_book(self, title, author, first_release_year, number_of_pages):
        self.file.write(f"{title},{author},{first_release_year},{number_of_pages}\n")

    def list_books(self):
        self.file.seek(0)
        for line in self.file:
            title, author, first_release_year, number_of_pages = line.strip().split(",")
            print("Book title:", title)
            print("Book author:", author)
            print("Book's first release year:", first_release_year)
            print("Book's number of pages:", number_of_pages)
            print()

    def remove_book(self, title):
        self.file.seek(0)
        lines = self.file.readlines()
        self.file.seek(0)
        for line in lines:
            if not line.startswith(title + ","):
                self.file.write(line)


lib = Library()

while True:
    print("""*** MENU ***
    1) List Books
    2) Add Book
    3) Remove Book
    q) Quit""")
    choice = input("Please choose an option: ")
    if choice == '1':
        lib.list_books()
    elif choice == '2':
        title = input("Enter book title: ")
        author = input("Enter book author: ")
        first_release_year = input("Enter first release year: ")
        number_of_pages = input("Enter number of pages: ")
        lib.add_book(title, author, first_release_year, number_of_pages)
    elif choice == '3':
        title = input("Enter book title to remove: ")
        lib.remove_book(title)
    elif choice.lower() == 'q':
        print("quitted")
        break
    else:
        print("Invalid choice. Please try again.")